### PR TITLE
Font enhancements - phase2 - compression, etc

### PR DESCRIPTION
**Pull request by jediunix**
1. Extended ASCII for fonts that have them.
2. Introduces lightweight font display iterator; `Font::bitmap()` removed.
3. Compresses fonts that benefit.
4. Eliminates ATMEGA2650 bootloader escape sequences.
5. Changes `Textbox` to display full character set (other than special
control characters).
6. Eliminates deprecated font methods.

Compressed fonts have a `compression_type` that is 1.  This allows future compression methods with modification to `CompressedFont`.

Iterator without compression causes a little under 2% speed drop.  Compression drops another 2%.

Compression saves:
29% 10x20
19% 12x24
 9% 6x10
13% 6x12
13% 6x9

If there were a "standard" way for users to customize features in Cosa without altering Cosa source (like an environment variable) it might be desirable to make extended ASCII an option.  A space/feature tradeoff.

BTW, benchmark numbers will not be comparable to previous since many character set sizes have changed.

### CODE REVIEW

**Comment by mikaelpatel** [comment]
I had a quick look at this PR. Have a few questions; What do you think about updating the Font class to handle compression types(0 for no compression, and 1 for the new type) instead of introducing a new class. Also it seems like that a Bitmap class is needed for the access iterator, e.g. Canvas::Bitmap::Iterator with begin() and next() member functions. The display_begin/next naming seems misleading. 

There might be a need for a simple compression method that removes any lines that are zero at the end of the character bitmap. 

I also saw that the PR removes the deprecated member function. No problem with that. 

Cheers!

**Comment by jediunix** [comment]
Yes, the Font class could be changed that way.  In addition to the compression type it would also always have a pointer to an offset table that would be unused for uncompressed fonts.

I guess a way to help determine the path is what happens when somebody comes up with some elegant new compression scheme that requires additional types of data?  If it has to be subclassed then the benefit of putting everything in Font is gone.  Another possibility is that the character lookup table could be moved into the bitmap itself eliminating the need for another variable.  That would require pulling 16 bits out of 2 bytes - not a big deal but not very elegant either.

I suppose glyph_begin/next would be better.

The iterator has to be within the context of the font it is associated with since the font is the only thing that knows how to iterate (in any compressed font that is).  It can't be a simple bitmap iterator in Canvas.  It could be a Font::Iterator class although the font has to be associated with it in the constructor.  It would basically be the Glyph we looked at earlier.  I don't have a problem with that approach however it could add some overhead with creating and destroying an object for every character.

Not sure what you mean by *lines that are zero at the end of the character bitmap*.  Are you referring to the typical blank column at the right side of a glyph?  Its pretty common for there to be a blank column on the left as well.  The encoding doesn't know anything about width so it will compress the end of one band and the beginning of another.  I suppose one could implement bit fields for blank rows and columns.  Full RLE may also benefit the larger fonts.  There are lots of possibilities that could be experimented with.  The work is that some fonts will benefit and others won't.  I ran all the new ones through with this compression and most the smaller ones are worse with compression as one would expect.  I'm a little concerned that compression type may devolve into a bit field of compression techniques applied - or every combination becoming a new compression type.

Moving to an iterator requires getting rid of the bitmap() method so its a good time to toss all the deprecated ones.

**Comment by jediunix** [comment]
It looks like an alternative algorithm works better - eliminating any zero bytes in the bitmap and having a bitset for each character indicating the eliminated bytes.

However, I have to figure out how to handle atmega2560 escape sequence in the bitset.  (I suppose that blasted sequence could occur in the offset table too!)

I may have to steal bit(s) from the offset table entries.  What is a reasonable limit for the max font bitmap size?  16KB? 32KB?

**Comment by jediunix** [comment]
Closing for a better PR.

**Pull request closed without merging**
