### PR TITLE
Font compression and other enhancements

### PR DESCRIPTION
**Pull request by jediunix**
1. Extended ASCII for fonts that have them.
2. Introduces `Font::Glyph` iterator; `Font::bitmap()` removed.
3. Compresses fonts that benefit using a non-zero byte-present bitset algorithm.
4. Eliminates ATMEGA2650 bootloader escape sequences.
5. Changes Textbox to display full character set (other than special control characters).
6. Eliminates deprecated font methods.

Space savings:
```
Font10x20 overall compression: 37%
Font12x24 overall compression: 26%
Font6x10 overall compression: 26%
Font6x12 overall compression: 22%
Font6x9 overall compression: 31%
Font7x13 overall compression: 7%
Font7x13B overall compression: 1%
Font7x14 overall compression: 5%
Font8x13 overall compression: 16%
Font8x13B overall compression: 6%
Font8x16 overall compression: 3%
Font9x15 overall compression: 14%
Font9x15B overall compression: 2%
```

Performance of uncompressed fonts has essentially not changed.  Performance of compressed fonts has declined ~8%.

Benchmark numbers will not be comparable to previous version since many character set sizes have changed.

### CODE REVIEW

**Comment by mikaelpatel** [comment]
Thanks! This looks really nice. I will test it later this evening. Cheers! Mikael

**Comment by mikaelpatel** [comment]
Seems like 6X12 has a coding problem. 7X14B fails to build. A strange link problem. Looks like a missing constructor. Cheers!

**Comment by jediunix** [comment]
6x12 is probably correct.  The lowercase with bars over them appears to be in the original BDF.  The pictorial representation in the data header file is basically the raw info that was input from the BDF.  Those characters are in the unprintable part of the font which was not displayed before by the test program.

I just committed a fix for the 7x14B data file.  I thought I had tested all of them :)

**Comment by jediunix** [comment]
No idea where the commit went.  Doesn't show up here or as a new PR candidate...

It's just 1 line adding compression_type = 0 to 7x14B.h

**Comment by mikaelpatel** [comment]
Missed the position of the characters with bars. I see now that they where not printed before. Seems odd though :)

Things will happen in software. Just too much ripple effect and too little time :)

Great job - I must say again. Now I feel like it is time to start adding more Canvas Elements and integrate with the Menu and Registry. 

Cheers! Mikael

**Comment by jediunix** [comment]
I'll look into 6x12 more.

**Comment by mikaelpatel** [comment]
I will push the 7x14B update.

**Comment by jediunix** [comment]
The 6x12.bdf shows the bars in FontForge so they are definitely there.  No idea what good they are :)

**Pull request merged**
