### PR TITLE
Add submodules for libraries moved to separate github repositories

### PR DESCRIPTION
**Pull request by kc9jud**

### CODE REVIEW

**Comment by kc9jud** [comment]
If I understand GitHub's behavior correctly, this won't change the ZIP behavior. Users can still download and unzip libraries if they don't want to use git and/or submodules.

**Comment by mikaelpatel** [comment]
@kc9jud 
This PR can't be merged automatically as the branch/base is very out of date and there are a lot of conflicts.

**Comment by kc9jud** [comment]
Brought the branch up to date with the current master tip... the only conflict was doc/05-libraries.md, which I resolved manually.

**Comment by mikaelpatel** [comment]
@kc9jud Thanks for the extra effort.

**Pull request merged**
