### PR TITLE
Labels on Pro Mini "FTDI" connector were reversed.

### PR DESCRIPTION
**Pull request by jeditekunum**

### CODE REVIEW

**Comment by mikaelpatel** [comment]
Hum, seems like I copied that off a clone (which actually has the pins reversed).

**Comment by jeditekunum** [comment]
@mikaelpatel 

That wasn't very nice of them :)

Mine is a clone too. So I guess the change needs to go further - indicating that it could be either way?

**Comment by mikaelpatel** [comment]
Let us stick to the original layout. In any case one should alway check the screen-print before connecting the board.

**Comment by mikaelpatel** [comment]
@jeditekunum 
Thanks for the update.

**Pull request merged**
